# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19a6QVQq1uluspY5JSOBPdty5RBEN6mKe
"""

import streamlit as st
import pandas as pd

st.title("Job Listing Clusters")

# File uploader
uploaded_file = st.file_uploader("Upload clustered_jobs.csv", type="csv")

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    clusters = df['Cluster'].unique()

    cluster_selected = st.sidebar.multiselect("Select clusters", clusters)

    if cluster_selected:
        filtered = df[df['Cluster'].isin(cluster_selected)]
        st.write(filtered)
    else:
        st.write(df)
else:
    st.warning("Please upload the 'clustered_jobs.csv' file to continue.")
